### ISSUE TITLE
Occasionally throws std::logic_error

### ISSUE THREAD

**Issue by MagpieEmbedded** [Shachlan/DataOrientedDemo#2]
Even on the simple case of 1 model, 1 animation per model and 1 experiment, occasionally the program will fail:

```bash
$ ./check 1 1 1
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

I have had issues getting it to ever run with any of these numbers larger than 1.

I'm running on Ubuntu via WSL with g++ 9.3.0

Any ideas what this could be?

**Comment by Shachlan** [comment]
Thanks, fixed.

I'd be glad if you could double check on your end.

**Comment by MagpieEmbedded** [comment]
Thanks, seems to be working a lot better now, have run it with 100 of each argument!
